/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rmELHShWk6e5tA9aoasW9J

import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: rmELHShWk6e5tA9aoasW9J/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: rmELHShWk6e5tA9aoasW9J/projectcss

const data = {
  base: projectcss.plasmic_tokens,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
