/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rmELHShWk6e5tA9aoasW9J

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsegT9UoPi5LWq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: egT9uoPI5LWq/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsegT9UoPi5LWq
});
